Ftppush - Fix issue #139 and prepare configurable ftp port
roleoroleo/sonoff-hack pull request #141
Opened 2023-04-05 21:36 UTC by couriersud

- add sonoff-hack/usr/bin/rmdir to enable rmdir
- above fixes issue #139 
- @darkxt proposed more code changes (see #139). This PR follows a minimum changea approach an fixes the missing rmdir
- The PR allows replaces the hardcoded port 21 for FTP with a variable called `FTP_PORT`
- This may be extended using `get_config` to provide a ftp port configured in the UI

2023-04-06 00:20 UTC, darkxst requested changes
Thanks for the PR!

2023-04-06 00:20 UTC, darkxst commented on src/static/static/sonoff-hack/script/ftppush.sh
> +	FTP_PORT=21
This is not a file users should be editing to change ports.

FTP_PORT should be added to the sonoff-hack `system.conf` file, so you can use the `$(get_config ....)` command here.
It can then also be added to the Web UI fairly easily also with just a small block of HTML.

2023-04-07 09:33 UTC, darkxst reviewed
Also make sure to add this new option to `sonoff-hack/script/check_conf.sh`

That will handle adding the new key on upgrade to new firmware version.

2023-04-08 01:37 UTC, darkxst reviewed
just a couple of nitpicks.

Also you could probably squash all these commits into 1 or 2 commits.

2023-04-08 01:37 UTC, darkxst commented on src/static/static/sonoff-hack/script/ftppush.sh
> +			[ -z "`find $d -type f`" ] && $SONOFF_HACK_PREFIX/usr/bin/rmdir $d
This is in PATH, so no need to specify the full path here.

Also the following lines near the top of this file could be deleted. These are only here for historical reasons, both are already set via system.conf and/or dropbear for login shell. 
```
# Setup env.
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/mmc/sonoff-hack/lib
export PATH=$PATH:/mnt/mmc/sonoff-hack/bin:/mnt/mmc/sonoff-hack/sbin:/mnt/mmc/sonoff-hack/usr/bin:/mnt/mmc/sonoff-hack/usr/sbin
```

2023-04-08 01:37 UTC, darkxst commented on src/www/httpd/htdocs/pages/eventsdir.html
> +                    <tr class="row">
This would probably be more logical to go right FTP_HOST setting.

2023-04-08 12:37 UTC, couriersud commented
Sorry, the next window to work on this is in a couple of weeks. I have already invested a lot more time than anticipated into this. 
- number of commits -> commits can be squashed when the PR is applied. 
You will see another proof-of-concept PR to document a possible solution for immediate motion feedback by mqtt on S-CAM devices.

2023-04-08 13:45 UTC, darkxst commented
They are only very minor edits, just use git rebase to apply the edits to the commits and force push your branch again ;)

2023-04-09 21:49 UTC, couriersud commented
I have applied your comments.

2023-04-11 10:00 UTC, roleoroleo commented
Thank you for this PR.

2023-04-11 10:00 UTC, merged